<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="user-PC" name="exampletest3" tests="1" failures="1" timestamp="17 Jul 2014 10:46:56 GMT" time="0.003" errors="0">
  <testcase name="testFinalMessage" time="0.001" classname="com.assignment52.TestNGSuiteTest.Test3">
    <failure type="java.lang.AssertionError" message="expected [Hi testng is working finerevathi] but found [Hi testng is working fine!revathi]">
      <![CDATA[java.lang.AssertionError: expected [Hi testng is working finerevathi] but found [Hi testng is working fine!revathi]
	at com.assignment52.TestNGSuiteTest.Test3.testFinalMessage(Test3.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testFinalMessage -->
</testsuite> <!-- exampletest3 -->
